### ISSUE TITLE
File saves to weird location

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2021sp-420-JINXS#115]
**As a** User
**When** I save a file
**Then** It should save to the location where I launched the program (if in CLI) or use a file chooser prompt (if in GUI)

Currently, there is zero documentation on where the file actually saves and the user is expected to "just remember" valid names of what was saved in the past.

**Comment by natshenk** [comment]
Feels like a bug I can handle easily. I got this one

**Comment by willkill07** [comment]
This still isn't done after 21 days :(  ((very unhappy client))

**Comment by natshenk** [comment]
https://github.com/mucsci-students/2021sp-420-JINXS/issues/160#issue-845324998
