### ISSUE TITLE
Task: OS Appropriate File Slashes

### ISSUE THREAD

**Issue by Irblake14** [mucsci-students/2021sp-420-JINXS#160]
- [x] Change the default save location to the top-level of the project
- [x] Add the option to specify an OS-appropriate file path to the save command in the CLI
- [x] Add the option to specify an OS-appropriate file path to the load command in the CLI
- [ ] Tests

Primary: @natshenk
Secondary: @JonathanWilkins1
Color: Green
Actual Color:
Actual Time:

**Comment by natshenk** [comment]
#155
