### ISSUE TITLE
Task: Design the relationship arrows so that they avoid collisions/overlaps

### ISSUE THREAD

**Issue by SimonS1231** [mucsci-students/2021sp-420-JINXS#161]
- [x] Actually implement drawable arrows
- [x] Ensure that they actually move with the draggable classboxes
- [ ] Change how arrows interact with other arrows when they are supposed to collide
- [ ] TEST!!!!

Primary: @Xpagan
Secondary: @Irblake14
Color: Purple 
Actual Color:
Actual Time:

**Comment by JonathanWilkins1** [comment]
#150

**Comment by JonathanWilkins1** [comment]
We didn't end up making them fully "magic arrows" :(
