### ISSUE TITLE
Task: Tab Completion ++

### ISSUE THREAD

**Issue by Irblake14** [mucsci-students/2021sp-420-JINXS#163]
- [x] Implement a list of commands that can be used to predict what the user wants to type
 - [x] Make sure it can predict names of classes and their various attributes and relationships
 - [x] Tests

 Primary: @SimonS1231
 Secondary: @JonathanWilkins1
 Color: Purple
 Actual Color: Purple
 Actual Time: 3 hours

**Comment by JonathanWilkins1** [comment]
#126
