### ISSUE TITLE
Task: Implement class name restrictions

### ISSUE THREAD

**Issue by Irblake14** [mucsci-students/2021sp-420-JINXS#60]
- [x] Wait for reorganize commands 
- [x] Check if the request class name to add contains numbers or special characters (including spaces will trigger the too many arguments check)
- [x] Print out/display a message to the user if the name is invalid

Primary: @natshenk
Secondary: @JonathanWilkins1
Color: Grey 
Actual Color: Grey
Actual Time: 15 minutes

**Comment by natshenk** [comment]
Done.
